{application,mslog,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{mslog_app,[]}},
              {env,[]},
              {modules,[dynamic_compile,mslog,mslog_app,mslog_logger,
                        mslog_logger_h,mslog_loglevel,mslog_sup]}]}.
